import { readFileSync, writeFileSync } from "node:fs";

const packagePath = new URL("../frontend/package.json", import.meta.url);
const backendPath = new URL("../backend/app/version.py", import.meta.url);
const pkg = JSON.parse(readFileSync(packagePath, "utf8"));
const argument = process.argv[2];
const version = argument === "--check" ? pkg.version : argument;
const identifier = "(?:0|[1-9][0-9]*)";
const prerelease = "(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)";
const semver = new RegExp(`^${identifier}\\.${identifier}\\.${identifier}(?:-${prerelease}(?:\\.${prerelease})*)?$`);

// Omit build metadata (+...) so the version can also be used as a Docker tag.
if (!version || !semver.test(version)) {
  throw new Error("Usage: node scripts/set-version.mjs 0.1.0-dev.2 (or --check)");
}
const backendSource = `# Generated by scripts/set-version.mjs; edit versions with that command.\nAPP_VERSION = "${version}"\n`;

if (argument === "--check") {
  if (process.env.RELEASE_VERSION && process.env.RELEASE_VERSION !== version) {
    throw new Error(`Requested release must match application version ${version}.`);
  }
  if (readFileSync(backendPath, "utf8").replaceAll("\r\n", "\n") !== backendSource) {
    throw new Error("Frontend/backend version mismatch; run scripts/set-version.mjs with the desired version.");
  }
  if (process.env.GITHUB_REF?.startsWith("refs/tags/") && process.env.GITHUB_REF !== `refs/tags/v${version}`) {
    throw new Error(`Release tag must be v${version}, matching the application version.`);
  }
  console.log(`Version consistency OK: ${version}`);
} else {
  pkg.version = version;
  writeFileSync(packagePath, JSON.stringify(pkg, null, 2) + "\n");
  writeFileSync(backendPath, backendSource);
  console.log(`Frontend and backend version set to ${version}`);
}
